### ISSUE TITLE
Considerar el uso de comillas para los términos compuestos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#27]
Ejemplo, si el usuario pone "Malaria Vaccines", la herramienta ya sabe que el término es Malaria Vaccines y no Malaria y Vaccines.

**Comment by nietodaniel** [comment]
Esto ya está implementado, los únicos separadores son AND, OR, NOT, y los parentesis. Sin embargo se adicionó el placeholder que aclara esto

**Comment by renatomurasaki** [comment]
Continua con le mismo comportamiento.

**Comment by renatomurasaki** [comment]
Ahora aparece un internal server error
![image](https://user-images.githubusercontent.com/1226218/65906096-3da0e700-e398-11e9-8efc-ad902748c1e7.png)

**Comment by nietodaniel** [comment]
Resulto. Había entenido mal este punto.
Ya el algoritmo lo detecta. Por alguna razón se había cambiado el * por +
En vez de Yellow*fever, estaba enviando Yellow+fever.
Ahora funciona bien

**Comment by renatomurasaki** [comment]
poniendo "yellow fever" sale el error que sigue

![image](https://user-images.githubusercontent.com/1226218/66054383-43b6d500-e50a-11e9-80a9-772f9a2c31f6.png)
