### ISSUE TITLE
Cuando se apaga la ecuación de búsqueda para crear otra, la herramienta está manteniendo el histórico de términos explorados anteriormente

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#30]

**Comment by nietodaniel** [comment]
Respecto a esto, no entiendo bien a qué te refieres.

Lo que hace la app es que importa todos los datos y quedan almacenados en
el frontEnd, posteriormente dependiendo de si el usuario decide usar o no
ese keyword se usan esos datos

**Comment by nietodaniel** [comment]
Voy a tratar de tener todo listo de aquí a las 4 pm hora brasil!

**Comment by renatomurasaki** [comment]
Si el usuario cambia de idea y quiere quitar un término o reempezar con otra estrategia, el sistema siempre trae el historico de la búsqueda anterior.

**Comment by nietodaniel** [comment]
Hola Renato, según te entiendo, lo que quieres es que si tengo...
* **Búsqueda Inicial :** Dengue AND zika
* **Búsqueda Modificada luego de borrar todo:** Chikungunya
Deseas que no aparezca nada relacionado a dengue y zika, cierto? Esto es fácil de implementar

Sin embargo si te refieres a eliminar los datos previos, ocultos, y transparentes al usuario, que están cacheados en la presentación, tengo muchos argumentos en contra, e hice este resumen y diagrama para explciarte el cómo y por qué del diseño del controlador-servicio DeCS:
* No es necesario realizar de nuevo la búsqueda porque ya toda la información esta obtenida y guardada en un campo oculto en la presentación, reduciendo la carga
* No se pierde información porque se almacena la información completa en formato tree_ids,, indepependiemente de qué escoja el usuario
* Cada vez que se ejecuta el controlador DeCS, este obtiene la información ya obtenida, y la procesa junto con la información nueva, para obtener los resultados, en formto Terms, esto se hace al final porque en este proceso se pierde detalle y relieve de la información, ya que se mezclan todos los lenguajes en un solo array 
* Lo que escoge el usuario se almacena en otra variable, independiente de eso, por lo que está hecho a prueba de fallos. Los datos se almacenan en variables indpendientes y el controlador procesa toda la información

![image](https://user-images.githubusercontent.com/36118634/65534949-13e24e80-dec6-11e9-8bf2-9ff4abd1d3a7.png)

**Comment by renatomurasaki** [comment]
@nietodaniel es exactamente este ejemplo que mencionaste.

**Comment by renatomurasaki** [comment]
Continua el mismo comportamiento.
![image](https://user-images.githubusercontent.com/1226218/65721371-4d5eb980-e080-11e9-9fa4-844833028f0c.png)

Empece con la palabra dengue y hice el expand. Volvi y borré la palabra dengue y puse malaria. Hice lo mismo procedimiento después con la palabra yellos fever.
