### ISSUE TITLE
Implementar el paso "Improve Search"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#31]
Creo que el nombre "Improve search" no sea lo más adecuado. Quizas podría ser "Include no DeCS/MeSH terms".

La idea es que el usuario ponga cualquier ecuación de búsqueda. La herramienta debe tomar lo que el usuario ha puesto y añadirlo a la ecuación final. 

Ejemplo: supongamos que el usuario ponga en la etapa P la expresión amazonia and (brasil or brazil) en el paso "improve search". La herramienta debe tomar la ecuacion del P y añadir esta expresion, es decir (ecuacion del P) OR (improve search) -> (ecuacion del P) OR (amazonia and (brasil or brazil)).

**Comment by nietodaniel** [comment]
Implementado! Lo incluí como una pequeña función que agrega el texto al final de la ecuación y la salva en el frontend, por si el usuario vuelve a entrar al mismo menu, para que no se pierda.

Se me ocurre, para más adelante, incluir la opción de que el usuario, con un checkbox, la una con un AND, OR o NOT, a su gusto
