### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#32]
El botón de expand DeCS/MeSH terms funciona solamente una vez. Después dispara un Internal Server Error y oculta el botón Results. Para probar nuevamente necesito hacer reload.

**Comment by renatomurasaki** [comment]
Este error continua ocurriendo y se reproduce de la misma manera.

**Comment by nietodaniel** [comment]
Resuelto. Hice muchas pruebas y no logré hacer que la app fallara. Solamente existe un error al final, en la generación de la ecuación, pero se me ocurre implementar una estrategia en 3 capas

Capa 1 - Intenta generar resultados avanzados.
    -Prueba el número de resultados y la integridad de la ecuación
    - Si la capa falla, prosigue a la segunda capa

Capa 2- Intenta Genera nueva ecuación a partir solamente de las palabras clave, ignorando parentesis, se pierde muy poca información y se mantienen los datos no seleccionados y las free keywords
    -Prueba el número de resultados y la integridad de la ecuación
    - Si la capa falla, prosigue a la segunda capa

Capa 3- Genera nueva ecuación desde cero, solo a partir de las palabras claves y datos recientemente seleccionados. Esta ecuación no falla y es acertada


Dudas:
Si incluso en la capa 3 no se generan resultados positivos, quiere decir que el discriminante para saltar de capa, no es el numero de resultados obtenidos, sino la integridad de la ecuacion
