### ISSUE TITLE
Problemas en la recuperación de sinónimos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#33]
Ejemplo con Dengue. Faltan sinónimos para Dengue, pero creo que eso es parámetro de configuración. En Dengue Virus, además de faltar sinónimos (muestra menos sinónimos comparado a los de Dengue), hay sinónimos que no existen: es el caso de la repetición dos veces de Dengue Virus. En Severe Dengue y Dengue Vaccines pasa lo mismo, pues aparece dos veces Severe Dengue y Dengue Vaccines como sinónimo.

**Comment by nietodaniel** [comment]
Voy a revisarlo un poco más, con un poco más de calma, ya que no ha habido tiempo de hacer estos análisis pero como dices, yo crería que es un parámtetro de configuración. Actualmente estos son los parámetros que usa el explorador de DeCS para cada operación

        'MaxExploringLoops' => 5,
        'MaxTreesPerKeyword' => 10,
        'MaxDescendantsPerTree' => 10,
        'MaxDescendantsDepth' => 5,
        'AddDescendantsToMainTrees' => true,
        'AddRelatedTreesToMainTrees' => true,
        'AllValidLanguages'=>[
            'en',
            'es',
            'pt'
        ]

Voy a revisar un poco la estrcutura interna, buscando que los parámetros se acomoden a la respuesta intiutivamente correcta

**Comment by renatomurasaki** [comment]
Aún no recupera correctamente los sinónimos:

Respuesta del webservice (http://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs/?words=dengue%20virus&lang=i):
```
<synonym_list>
<synonym>Breakbone Fever Virus</synonym>
<synonym>Breakbone Fever Viruses</synonym>
<synonym>Dengue Viruses</synonym>
<synonym>Fever Virus, Breakbone</synonym>
<synonym>Fever Viruses, Breakbone</synonym>
<synonym>Virus, Breakbone Fever</synonym>
<synonym>Virus, Dengue</synonym>
<synonym>Viruses, Breakbone Fever</synonym>
<synonym>Viruses, Dengue</synonym>
</synonym_list>
```
http://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs/?words=dengue%20virus&lang=e
```
<synonym_list>
<synonym>Virus de la Fiebre Rompehuesos</synonym>
</synonym_list>
```
http://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs/?words=virus%20dengue&lang=p
```
<synonym_list>
<synonym>Vírus da Febre Quebra-Ossos</synonym>
</synonym_list>
```
Pantalla de la herramienta:

![image](https://user-images.githubusercontent.com/1226218/65720969-7b8fc980-e07f-11e9-831b-0f28ce42b3c5.png)

Creo q nos muestra todos los sinónimos por cuenta de configuración, sin embargo, los términos Dengue Virus y Virus del Dengue que se repiten 2 veces cada uno no son sinónimos. Son el proprio descriptor que se repite en el listado de sinónimos.

**Comment by renatomurasaki** [comment]
Aún siguen los mismos problemas

**Comment by nietodaniel** [comment]
Resuelto. El algoritmo explora dengue*virus en los tres lenguajes en, es pt

http://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs/?words=dengue%20virus&lang=pt
http://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs/?words=dengue%20virus&lang=es
http://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs/?words=dengue%20virus&lang=en

Obteniendo un total de 4 arboles.

Posteriormente, explora los lengaujes faltantes en cada arbol. Este paso es un paso absolutamente clave y relevante para el negocio y expondré por qupe...

Si buscas Yellow Fever en portugues no vas a encontrar ningun resultado
http://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs/?words=yellow%20fever&lang=pt

En cambio nuestro buscador busca en todos los lengauejs, obtendrá 3 tree_ids en la versión en inglés
http://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs/?words=yellow%20fever&lang=en

Posteriormente, explora todos los arboles, principales y descendientes en el lenguaje requerido, en este caso PT, Y excluye los lenguajes no requeridos por el usuario

**Comment by renatomurasaki** [comment]
Todavía se repite como sinónimo el proprio término. Ahora me parece que solamente se está incorporando el idioma inglés. En la prueba hecha con malaria, seleccionando solamente en término malaria, los sinónimos que se muestran incluyen de aquellos términos no seleccionados. Eso tiene relación con el error reportado en el issue #44

**Comment by renatomurasaki** [comment]
Resolver el problema de los descendientes para no repetir los sinónimos en más de una pestaña. No incluir los sinónimos de los descendientes en el término padre.

**Comment by renatomurasaki** [comment]
@nietodaniel ahora la recuperación de los sinónimos parece estar correcta. 

En este caso, faltaria solamente quitar de la lista de sinónimos el proprio término. Ejemplo: en la lista de sinónimos del término "Severe Dengue", aparecen dos veces "Severe Dengue" (idioma inglés) y quatro veces "Dengue Grave" (idiomas portugués y español)

**Comment by nietodaniel** [comment]
Corregido. Además de esto se especifico que la primera letra de todas las palabras fuera mayúscula, y que al final se removieran los elementos repetidos.

**Comment by renatomurasaki** [comment]
Excelente! Ahora funciona correctamente!
