### ISSUE TITLE
Cuando el resultado de búsqueda por un concepto retorna muchos descriptores, no es posible visualizarlos en una unica pantalla, tampoco se puede acceder a los botones de acción

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#34]
Hacer un ejemplo con la palabra heart

**Comment by nietodaniel** [comment]
Corregido de dos modos. Primero, pondré un scroll que permita expandir la vista. Segundo, modificaré los parametros del explorador de DeCS para limitar los resultados, ya que evidentemente eso no solo representa un gasto innecesario de recursos sino que además el usuario no necesita tanta información
