### ISSUE TITLE
Revisar comportamiento de los botones PICO cuando se hacen cambios después de la búsqueda realizada

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#37]
Sugerencia de una sesión virtual para discutir este tema

**Comment by nietodaniel** [comment]
Estamos de acuerdo. Voy a dejarlos funcionando y esperaré tu retroalimentación en una reunión, quedo pendiente de la fecha, por ahora para esta entrega estará solucionado hasta donde lo considero correcto

**Comment by renatomurasaki** [comment]
Si cambio la ecuación, el botón population mantiene na ecuación anterior, mismo que en la caja de búsqueda tengamos la nueva. La imagen abajo muestra eso. Otro problema es que el botón "Update results" no está actualizando la ecuación ni tampoco la cantidad de documentos regresados.

![image](https://user-images.githubusercontent.com/1226218/65907086-07646700-e39a-11e9-9e24-93c4f418014d.png)

**Comment by nietodaniel** [comment]
Solucionado! Terminando de hacer pruebas respecto a esto

**Comment by nietodaniel** [comment]
Corregido. Se hizo mucho enfásis en el proceso de flujo de información, garantizando que la entregada fuera veraz.

Sin embargo existe un problema de integración, ya que cuando la ecuación es muy larga, está no es recibida por el server de búsqueda. Plantearía enviar la información mediante POST a un servicio expuesto por esta app y que finalmente se genere un link de acceso fácil. Si existe otro modo más simple, actualmente no lo conozco y tocaría investigar, pero claramente es algo fácil. Sin embargo, como mencioné en el correo previamente, los temas de integración con las tecnologías actuales de BIREME, están por fuera del alcance del proyecto. Aunque tengo toda la disposición y ánimos de cooperar y ver cómo podemos resolver esto!

**Comment by nietodaniel** [comment]
![BIREME integration](https://user-images.githubusercontent.com/36118634/66583158-7edb8880-eb48-11e9-9204-ea12ead1ebb7.png)

Esta sería la forma en la que yo plantearía que se podría resolver, pero no conozco mucho del tema

**Comment by renatomurasaki** [comment]
La prueba efectiva de este issue depende de la solución del issue #39

**Comment by nietodaniel** [comment]
Solucionado comportamiento de botones

**Comment by renatomurasaki** [comment]
Paso 1: expandir la palabra zika y escoger los descriptores Zika Virus y Zika Virus Infection con todos los sinónimos

`(Zika OR "Zika Virus" OR Zikv OR "Virus Zika" OR "Virus De Zika" OR "Virus De La Fiebre Zika" OR "Virus Del Zika" OR Zikavirus OR "Vírus Zika" OR "Vírus Da Febre Zika" OR "Vírus Da Zika" OR "Vírus De Zika" OR "Zika Virus Infection" OR "Zika Virus Disease" OR "Zika Fever" OR "Zikv Infection" OR "Infección Por El Virus Zika" OR "Enfermedad Del Virus Zika" OR "Enfermedad Por Virus Zika" OR "Enfermedad Por Zikv" OR "Enfermedad Por Zika" OR "Enfermedad Por Zika Virus" OR "Enfermedad Por El Virus Zika" OR "Enfermedad Por El Virus De Zika" OR "Enfermedad Por El Virus Del Zika" OR "Enfermedad Por El Zikavirus" OR "Fiebre Zika" OR "Fiebre Por Virus Zika" OR "Fiebre Por El Virus Zika" OR "Infección Del Virus Zika" OR "Infección Por Virus Zika" OR "Infección Por Vzika" OR "Infección Por Zikv" OR "Infección Por Zika Virus" OR "Infección Por Zikavirus" OR "Infección Por El Virus De Zika" OR "Infección Por El Virus Del Zika" OR "Infecção Por Zika Virus" OR "Doença Pelo Vírus Zika" OR "Doença Pelo Zika Virus" OR "Doença Pelo Zikavirus" OR "Doença Por Vírus Zika" OR "Doença Por Zika Virus" OR "Febre Zika" OR "Febre Pelo Vírus Zika" OR "Febre Por Vírus Zika" OR "Febre Por Zika" OR "Febre Por Zika Virus" OR "Infeccção Por Zikv" OR "Infecção Pelo Zika Virus" OR "Infecção Pelo Zikavirus" OR "Infecção Por Vírus Zika" OR "Infecção Por Zika" OR "Infecção Por Zikavirus")`

Paso 2: quitar de la selección el descriptor Zika Virus Infection y mantener solamente el sinónimo Zikv del descriptor Zika Virus

`(Zika OR "Zika Virus" OR Zikv OR "Zika Virus Infection")`

Sucede que la ecuación mantuvo el descriptor Zika Virus Infection, lo cual habia sido quitado de la ecuación.
