### ISSUE TITLE
Al regresar al expand despúes de expandir los términos y quitar un término o sinónimo, la ecuación no es actualizada con estos cambios

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#39]

**Comment by renatomurasaki** [comment]
@nietodaniel ahora tenemos el mismo problema reportadeo en el issue #32

**Comment by nietodaniel** [comment]
Solucionado. Recomiendo cerrar este issue y seguir uno solo en el otro hilo

**Comment by renatomurasaki** [comment]
Todavía no está solucionado. Incluso hay un otro problema reportado en #44

**Comment by nietodaniel** [comment]
Corregido. Se hizo mucho enfásis en que la ecuación obtenida fuera de acuerdo a las palabras seleccionadas. Se hizo una revisión muy profunda del proceso y reconstrucción de varias partes

**Comment by renatomurasaki** [comment]
@nietodaniel Todavia persiste el error. Para reproduzir:

1) Palabra Dengue en la caja Population
2) Dejar solamente "Dengue Vaccines" con el flag de selecionado
3) Continuar adelante hasta producir la ecuación
4) Regresar al Expand
5) Continuar
6) Sacar el sinónimo Vacunas Contra El Dengue
7) Continuar adelante hasta producir la ecuación

Se notará que la ecuación aún tiene Vacunas Contra El Dengue.
También percebi que se adiciono otro término, además de Dengue Vaccines, la ecuación tampoco se actualiza.

**Comment by nietodaniel** [comment]
Vale. Revisandolo. No creo que demore más de 1 hora el proceso!

**Comment by nietodaniel** [comment]
Resuelto se reconstruyo el algoritmo de inclusión o exclusión de términos

**Comment by renatomurasaki** [comment]
@nietodaniel este issue está muy cerca de ser resuelto. Fucionaron las ediciones de ecuacion en quitar e incluir descriptores, sinonimos y free keywords. Sin embargo, cuando hay la presencia de free keywords y hago una edición quitando o incluyendo un descriptor o sinónimo, la ecuación resultante duplica la expresión que corresponde al free keyword. Eso no impacta el resultado de la recuperación de documentos, pero "sucia" la ecuación. Vea el ejemplo abajo:

Paso 1:
`(Zika OR "Zika Virus" OR Zikv OR "Virus Zika" OR "Virus De Zika" OR "Virus De La Fiebre Zika" OR "Virus Del Zika" OR Zikavirus OR "Vírus Zika" OR "Vírus Da Febre Zika" OR "Vírus Da Zika" OR "Vírus De Zika") OR (Ti:(Microcef*))`

Paso 2 (quitando el sinónimo Zikavirus):
`(Zika OR "Zika Virus" OR Zikv OR "Virus Zika" OR "Virus De Zika" OR "Virus De La Fiebre Zika" OR "Virus Del Zika" OR "Vírus Zika" OR "Vírus Da Febre Zika" OR "Vírus Da Zika" OR "Vírus De Zika") OR (Ti:(Microcef*)) OR (Ti:(Microcef*))`

**Comment by renatomurasaki** [comment]
@nietodaniel otro comportamiento equivocado encontrado:

Paso 1: expandir la palabra zika y escoger los descriptores Zika Virus y Zika Virus Infection con todos los sinónimos

`(Zika OR "Zika Virus" OR Zikv OR "Virus Zika" OR "Virus De Zika" OR "Virus De La Fiebre Zika" OR "Virus Del Zika" OR Zikavirus OR "Vírus Zika" OR "Vírus Da Febre Zika" OR "Vírus Da Zika" OR "Vírus De Zika" OR "Zika Virus Infection" OR "Zika Virus Disease" OR "Zika Fever" OR "Zikv Infection" OR "Infección Por El Virus Zika" OR "Enfermedad Del Virus Zika" OR "Enfermedad Por Virus Zika" OR "Enfermedad Por Zikv" OR "Enfermedad Por Zika" OR "Enfermedad Por Zika Virus" OR "Enfermedad Por El Virus Zika" OR "Enfermedad Por El Virus De Zika" OR "Enfermedad Por El Virus Del Zika" OR "Enfermedad Por El Zikavirus" OR "Fiebre Zika" OR "Fiebre Por Virus Zika" OR "Fiebre Por El Virus Zika" OR "Infección Del Virus Zika" OR "Infección Por Virus Zika" OR "Infección Por Vzika" OR "Infección Por Zikv" OR "Infección Por Zika Virus" OR "Infección Por Zikavirus" OR "Infección Por El Virus De Zika" OR "Infección Por El Virus Del Zika" OR "Infecção Por Zika Virus" OR "Doença Pelo Vírus Zika" OR "Doença Pelo Zika Virus" OR "Doença Pelo Zikavirus" OR "Doença Por Vírus Zika" OR "Doença Por Zika Virus" OR "Febre Zika" OR "Febre Pelo Vírus Zika" OR "Febre Por Vírus Zika" OR "Febre Por Zika" OR "Febre Por Zika Virus" OR "Infeccção Por Zikv" OR "Infecção Pelo Zika Virus" OR "Infecção Pelo Zikavirus" OR "Infecção Por Vírus Zika" OR "Infecção Por Zika" OR "Infecção Por Zikavirus")`

Paso 2: quitar de la selección el descriptor Zika Virus Infection y mantener solamente el sinónimo Zikv del descriptor Zika Virus

`(Zika OR "Zika Virus" OR Zikv OR "Zika Virus Infection")`

Sucede que la ecuación mantuvo el descriptor Zika Virus Infection, lo cual habia sido quitado de la ecuación.
