### ISSUE TITLE
La construcción de la ecuación no obedece la selección del usuario en las etapas intermedias

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#44]
Reproducción:
1) Pongo dengue y expando
2) Dejo seleccionado solamente Dengue Vaccines
3) Dale continuar hasta la construcción de la ecuación

La ecuación resulta en 

`(((dengue OR Dengue OR "Break Bone Fever" OR "Break-Bone Fever" OR "Breakbone Fever" OR "Classical Dengue" OR "Classical Dengue Fever" OR "Classical Dengue Fevers" OR "Classical Dengues" OR "Dengue Fever" OR "Severe Dengue" OR "Dengue Hemorrhagic Fever" OR "Dengue Shock Syndrome" OR "Severe Dengues" OR "Philippine Hemorrhagic Fever" OR "Singapore Hemorrhagic Fever" OR "Thai Hemorrhagic Fever" OR "Hemorrhagic Dengue" OR "Hemorrhagic Dengues" OR "Dengue Virus" OR "Breakbone Fever Virus" OR "Breakbone Fever Viruses" OR "Dengue Viruses" OR "Severe Dengue" OR "Dengue Hemorrhagic Fever" OR "Dengue Shock Syndrome" OR "Severe Dengues" OR "Philippine Hemorrhagic Fever" OR "Singapore Hemorrhagic Fever" OR "Thai Hemorrhagic Fever" OR "Hemorrhagic Dengue" OR "Hemorrhagic Dengues" OR "Dengue Vaccines")))`

como si no hubiera seleccionado solamente Dengue Vaccines.

**Comment by renatomurasaki** [comment]
Todavia no respecta la decisión del usuario, tanto en quitar como en añadir términos.

**Comment by nietodaniel** [comment]
Resuelto. Se reconstruyo el algoritmo
