### ISSUE TITLE
Verificación de obtención de variables del ambiente  de prueba.  En el script debe analytics debe aparecer el id. Si no aparece es necesario utilizar php artisan installPICO

### ISSUE THREAD

**Issue by nietodaniel** [bireme/PICO-BackEnd#56]

**Comment by nietodaniel** [comment]
![image](https://user-images.githubusercontent.com/36118634/66586211-dd573580-eb4d-11e9-9d9f-0dcc6042da13.png)
Aquí está un ejemplo de cómo se ve cuando no aparece debido a que no se utilizo php artisan installPICO

**Comment by renatomurasaki** [comment]
Aún no hemos configurado GA

**Comment by viniciusandrade** [comment]
Daniel, hemos informado el ID de GA en el archivo .env y ejecutado el comando php artisan installPICO

Este fue el output:

1. clearing cache... Success
2. clearing config cache... Success
3. Autoloading dump... Success
4. clearing views... Success
5. clearing routes... Success
6. Generating ide helper...**Exception: There was no view id specified. You must provide a valid view id to execute querys on Google Analytics.**
Skipping \Spatie\Analytics\AnalyticsFacade.
**Exception: There was no view id specified. You must provide a valid view id to execute querys on Google Analytics.**
Skipping \Spatie\Analytics\AnalyticsFacade.

Duda: Las excepciones generadas son normales o debo hacer algo mas en el ambiente?

**Comment by nietodaniel** [comment]
Vale, ya reviso!
Todavía sigo trabajando en la ecuación. Parece que fuera mucho lo que está
fallando, pero realmente es solo un método dentro de QueryBuild.

Es un poco complejo resolver qué palabras se van a usar cuando tenemos que
mezclar los datos presentes en el query manual, los previamente
seleccionados y los recién obtenidos. No se preocupen, va a quedar muy bien
y nos vamos a poder ir a descansar tranquilos este fin de semana con esto
listo!!

Un abrazo.

**Comment by nietodaniel** [comment]
En mi computador no aparece este error. Es más, ni siquiera aparece ese Facade entre los archivos. Esa es una de las dependencia que había eliminado. Creo que es necesario hacer composer update
![image](https://user-images.githubusercontent.com/36118634/66673816-08fa1e80-ec27-11e9-8f51-6180a38e1651.png)

**Comment by nietodaniel** [comment]
Instale la app en otra maquina y también me corrió sin problema. Estoy seguro que el problema es actualizar las dependencias usadas por composer

**Comment by viniciusandrade** [comment]
OK, ejecuté el comando **composer update** y ahora al ejecutar el php artisan installPICO no se presenta mas mensajes de error. Gracias.
