### ISSUE TITLE
Error en la ecuación cuando se borrar los términos previamente utilizados en free terms

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#57]
Primera ronda del expand resulto en 

`(((Dengue OR ("Vacunas Contra El Dengue" OR "Vacinas Contra Dengue" OR "Vacinas Contra A Dengue" OR "Vacinas Contra O Vírus Da Dengue")))) OR (Ti:(Vacina OR Vacuna OR Vaccine))`

La segunda ronda donde se quita los términos puestos en Free Terms (Ti:(Vacina OR Vacuna OR Vaccine)), la ecuación se queda así:

`((((Dengue OR ("Vacunas Contra El Dengue" OR "Vacinas Contra Dengue" OR "Vacinas Contra A Dengue" OR "Vacinas Contra O Vírus Da Dengue")))) OR (:))`

**Comment by nietodaniel** [comment]
No entiendo esto muy bien. De dónde sale ese Ti: en(Ti:(Vacina OR Vacuna OR Vaccine))
Esto es el texto del boton final?

**Comment by renatomurasaki** [comment]
Este texto yo lo puse en la última etapa de free terms, como he descrito en el issue cuando hablo de la segunda ronda del expand.

**Comment by nietodaniel** [comment]
Resuelto. Se incluyo ":" en el algoritmo de corrección de ecuaciones
