### ISSUE TITLE
Uso de índice de búsqueda con las opciones de índices del formulario

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#59]
Title, Abstract, DeCS/MeSH terms --> prefijo tw (hoy está ti)
Title --> prefijo ti (hoy está tw)

@viniciusandrade All Fields é tw por defecto?

**Comment by viniciusandrade** [comment]
@renatomurasaki, exacto. All Fields é tw por defecto.

**Comment by nietodaniel** [comment]
No entendí muy bien... Title, Abstract, DeCS/MeSH term por defecto?
Desde mi experiencia en búsquedas, esta es la mejor opción. La segunda mejor opción sería all fields

**Comment by nietodaniel** [comment]
Cuál es el prefijo para todos los campos? Acabo de ver que al enviar la ecuación sin descriptor de campo, la app de búsquedas de bireme asume que es tw

https://pesquisa.bvsalud.org/portal/?count=20&q=Dengue

**Comment by nietodaniel** [comment]
Para escoger si utilizamos tw o all por defecto habría que hacer un balance.
TW: Más específico, mejores resultados para un investigador con conocimientos avanzados
All fields: Menos específico. Una buena opción para investigadores con poca experiencia que necesiten que la búsqueda no de cero (0)

**Comment by viniciusandrade** [comment]
Daniel, no hay la opción de búsqueda en todos los campos. TW es nuestro índice mas amplio de consulta.

**Comment by nietodaniel** [comment]
Vale! Puedo acortar la ecuación, eliminando el tw ya que bireme toma las ecuaciones sin ningun descriptor de campo como tw por defecto?

**Comment by viniciusandrade** [comment]
Sí, puede acortar de la ecuación.

**Comment by nietodaniel** [comment]
Resuelto. Se eliminó All terms, y se acomodó el descriptor de campo
