### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#64]
Ocurre cuando se intenta expandir en la caja de Intervention y Outcomes

**Comment by nietodaniel** [comment]
No logro reproducir este error. Alguna búsqueda en específico?

**Comment by renatomurasaki** [comment]
Ocurre para cualquier situación. Expand la subecuación Population y después intente expandir algo en Intervention. Recibirás el error.

**Comment by nietodaniel** [comment]
No olviden hacer php artisan installPICO. Creo que esto fue lo que causó el error. Acabo de subir una nueva versión

**Comment by viniciusandrade** [comment]
OK Daniel, estoy siempre ejecutando el php artisan installPICO después de hacer git pull.
