### ISSUE TITLE
Botón Search results no se actualiza con los cambios de las subecuaciones del formulario PICO

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/PICO-BackEnd#67]

**Comment by nietodaniel** [comment]
En el diseño habíamos acordado que el botón search results había que presionarlo para que actualizara los resultados. No se actualiza solo

**Comment by renatomurasaki** [comment]
si, pero cuando se presiona no utiliza la ecuación actualizada. El otón Search results no se actualiza con **los cambios de las subecuaciones del formulario PICO**
